
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: lambda-s3-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                Resource:
                  - !Sub 'arn:aws:s3:::mybucketforlambda12'  # Replace with your bucket name
                  - !Sub 'arn:aws:s3:::mybucketforlambda12/*'  # Replace with your bucket name and prefix
  
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt MyLambdaRole.Arn
      Runtime: python3.9
      Handler: lambda.lambda_handler
      Code:
        S3Bucket: mybucketforlambda12
        S3Key: lambda.zip
      Tags:
        - Key: Name
          Value: MyLambdaFunction


















# AWSTemplateFormatVersion: "2010-09-09"
# Resources:
#   MyLambdaRole:
#     Type: 'AWS::IAM::Role'
#     Properties:
#       AssumeRolePolicyDocument:
#         Version: "2012-10-17"
#         Statement:
#           - Effect: Allow
#             Principal:
#               Service:
#                 - lambda.amazonaws.com
#             Action:
#               - 'sts:AssumeRole'
#       Path: /
#       Policies:
#         - PolicyName: root
#           PolicyDocument:
#             Version: "2012-10-17"
#             Statement:
#               - Effect: Allow
#                 Action: 's3:*'
#                 Resource: '*'
  
#   MyLambdaFunction:
#     Type: AWS::Lambda::Function
#     Properties:
#       Role: !GetAtt MyLambdaRole.Arn
#       Runtime: python3.9
#       Handler: lambda.lambda_handler
#       Code:
#         S3Bucket: mybucketforlambda12
#         S3Key: lambda.zip
#       Tags:
#         - Key: Name 
#           Value: MyLambdaFunction


















# version: 0.2
# phases:
#   install:
#     runtime-versions:
#       python: 3.11
#     commands:
#       - echo "Installing dependencies..."
#       - pip install -r requirements.txt -t lib
#   build:
#     commands:
#       - echo "Zipping deployment package..."
#       - cd lib
#       - zip -r9 ../deployment_package.zip .
#       - cd ..
#       - zip -g deployment_package.zip lambda_function.py
#   post_build:
#     commands:
#       - echo "Updating lambda Function..."
#       - aws lambda update-function-code --function-name github-lambda-demo --zip-file fileb://deployment_package.zip
#       - echo "DONE!!"